name: Page Update
description: Request changes or improvements to a page
title: "[Page]: "
labels: ["page"]

body:
  - type: input
    attributes:
      label: Page name or route
      placeholder: /chat, /login, /dashboard, etc.
    validations:
      required: true

  - type: textarea
    attributes:
      label: What change is required on this page?
      placeholder: UI update, content change, new section, logic fix, etc.
    validations:
      required: true
